### ISSUE TITLE
ShowPanelData 应该如何使用，能给个示例代码吗

### ISSUE THREAD

**Issue by sosloop** [IcePower/X-ET7#10]

**Comment by IcePower** [comment]
这个参数我是从字母哥的EUI里抄过来的。ShowPanelData 里只有一个参数 Entity ContextData，我猜测它的用法是向打开的界面传递参数。也可以根据需要往 ShowPanelData 里加入其他的字段，比如控制界面的弹出方式、释放策略等。
比如我现在要向 LobbyPanel 传个参数 LobbyPanelContext
```
[ChildOf(typeof(ShowPanelData))]
public class LobbyPanelContext: Entity, IAwake
{
    public string Name { get; set; }
}
```
在打开界面的地方这样使用：
```
ShowPanelData showPanelData = fuiComponent.AddChild<ShowPanelData>();
LobbyPanelContext lobbyPanelContext = showPanelData.AddChild<LobbyPanelContext>();
lobbyPanelContext.Name = "参数";
showPanelData.ContextData = lobbyPanelContext;
await fuiComponent.ShowPanelAsync(PanelId.LobbyPanel, showPanelData);
```
这样在 LobbyPanelSystem.OShow 里就可以打印出 lobbyPanelContext.Name 了：
```
LobbyPanelContext lobbyPanelContext = contextData as LobbyPanelContext;
Log.Info(lobbyPanelContext.Name);
```
其他地方可能还需要根据你的需求做一些修改。
不过我们项目里这块的代码有了一些改动，之后我可以提交一下。

**Comment by sosloop** [comment]
那 ShowPanelData  在哪销毁呢，每次打开都会创建

**Comment by IcePower** [comment]
fuiComponent.ShowPanelAsync 函数里会把 ShowPanelData 挂到界面上，界面销毁的时候 ShowPanelData 跟着销毁。
