### ISSUE TITLE
FUI的OnShow方法报错会卡死

### ISSUE THREAD

**Issue by nihanlong** [IcePower/X-ET7#15]
FUIComponentSystem的RealShowPanel方法中，是先调用OnShow方法，再设置VisiblePanelsDic。

如果OnShow方法报错了，就不会设置VisiblePanelsDic。

但此时UI已经打开了，执行关闭逻辑的时候，VisiblePanelsDic中找不到相关Id，就不会关闭界面，导致整个UI卡死。

感觉可以把VisiblePanelsDic的设置提前。

**Comment by IcePower** [comment]
好的，可以。
