### ISSUE TITLE
我从主分支拉代码下来想试着运行一下,然后总是报这个错

### ISSUE THREAD

**Issue by 510463496** [IcePower/X-ET7#17]
![image](https://user-images.githubusercontent.com/33546202/230869743-f4e9a2fc-432c-4661-a0c1-6404d26d3fd3.png)

然后我打印了location
![image](https://user-images.githubusercontent.com/33546202/230870066-e616eed4-d148-4784-935d-f4e266d6b260.png)

**Comment by 510463496** [comment]
换了GameTemplate分支可以了。 学习学习先

**Comment by IcePower** [comment]
GameTemplate 的代码很老了，我一会看看弄个使用步骤吧。

**Comment by 510463496** [comment]
感谢

**Comment by IcePower** [comment]
你这个问题应该是没有构建资源，先打开界面：YooAsset - AssetBundle Builder ，然后构建。

**Comment by storm1122** [comment]
> GameTemplate 的代码很老了，我一会看看弄个使用步骤吧。

hybirdCLR生成这里过不去 Exception: resolve assembly:Model 失败   需要什么操作吗

**Comment by IcePower** [comment]
> > GameTemplate 的代码很老了，我一会看看弄个使用步骤吧。
> 
> hybirdCLR生成这里过不去 Exception: resolve assembly:Model 失败 需要什么操作吗

不是很清楚了，我目前用的是 hybirdCLR 1.0版。
