### ISSUE TITLE
  ET0013 静态类函数引用存在环形依赖 请修改为单向依赖

### ISSUE THREAD

**Issue by xiantuan** [IcePower/X-ET7#21]
OS:WIN10;
Unity 2021.3.16f1
X-ET7 : 2023.4.25
IDE:Rider 2022.3.3
MSBuild: .Net6.0.408
编译出错。ET.7.2 是没问题的 
![image](https://user-images.githubusercontent.com/10727426/234147972-6d1048d3-2cb6-4e96-9f61-1bba503ca464.png)

**Comment by IcePower** [comment]
已修复
