### ISSUE TITLE
求救，proto生成报错

### ISSUE THREAD

**Issue by TapsJoy** [IcePower/X-ET7#22]
![QQ截图20230425210925](https://user-images.githubusercontent.com/111265430/234287045-5b154c13-6180-4344-a52d-1d9baedc04e7.png)
![QQ截图20230425210942](https://user-images.githubusercontent.com/111265430/234287066-a6f073eb-8c66-4eab-bd29-0179416efe17.png)

点击生成proto之后报错。这是我哪里操作不当么？

**Comment by IcePower** [comment]
你是不是没有 Build ET.sln
