### ISSUE TITLE
求救，关于FGUI的正确姿势。

### ISSUE THREAD

**Issue by TapsJoy** [IcePower/X-ET7#23]
我尝试使用FGUI添加面板。但是不能正确生成代码。
![QQ截图20230502215852](https://user-images.githubusercontent.com/111265430/235690800-31a2f3e4-7af1-45d8-a5a4-4b935f868048.png)

![aaa](https://user-images.githubusercontent.com/111265430/235691037-1e1ce4b7-eaed-4f80-b34f-165f7c24f956.png)

![QQ截图20230502220136](https://user-images.githubusercontent.com/111265430/235690864-46edaf95-9f54-4af2-98ef-5d04a9bde258.png)

点击了et_buildTool _ fui代码生成

但是似乎没什么反应。是我哪里搞错了么？

**Comment by IcePower** [comment]
应该不会呀，要不你先单步跟踪一下看看能不能找出问题。

**Comment by IcePower** [comment]
可能是导出代码有些边界情况没有处理好，你在MyLoginPanel里拖个文本进去，然后改下名字，比如叫"name"。然后再试试。
你操作的第2步用的是FairyGUI编辑器的导出功能吧，不是手动的吧。

**Comment by IcePower** [comment]
你这个MyLogin的包是在X-ET7项目里的FUIProject里建的吗？如果是另一个独立的FairyGUI工程的话，是会出现你这个错误的。因为代码导出功能读取的是FUIProject的xml

**Comment by TapsJoy** [comment]
> 你这个MyLogin的包是在X-ET7项目里的FUIProject里建的吗？如果是另一个独立的FairyGUI工程的话，是会出现你这个错误的。因为代码导出功能读取的是FUIProject的xml，不是导出到Unity里的文件。

我是在外面建的，有可能是这个问题，我试试。

**Comment by TapsJoy** [comment]
行了。
不过生成的代码里systemLanguage报错，我是不是多语言部分没设置？
![QQ截图20230505121455](https://user-images.githubusercontent.com/111265430/236377043-1fd7db8b-97bb-4b65-a80a-1f41eb959d5b.png)

**Comment by TapsJoy** [comment]
我先把这行删了。问题暂时解决了。

**Comment by IcePower** [comment]
嗯 是有这个问题，我改一下
