### ISSUE TITLE
huatuo在generate all的时候报错找不到model

### ISSUE THREAD

**Issue by 834153063** [IcePower/X-ET7#24]

**Comment by 834153063** [comment]
![image](https://user-images.githubusercontent.com/30400364/236207757-bddf2ed3-1698-4db2-9eae-97c01a2c59ec.png)
按照这个方式设置的，然后我想测试下热更功能，点huatuo的generate all的时候发现报错的

**Comment by IcePower** [comment]
已解决 [https://github.com/IcePower/X-ET7/commit/847d7f24d7668e09765b8155cfb149f3a7615d48](url)
