### ISSUE TITLE
求救，怎么设置FUI的主资源。

### ISSUE THREAD

**Issue by TapsJoy** [IcePower/X-ET7#26]
我按自己的需求改造HotUpdatePanel。改变之后的panel生成代码有点问题。

![QQ截图20230507120255](https://user-images.githubusercontent.com/111265430/236657116-fa1bbbe0-0c36-40ce-9ac2-286d95583c16.png)

HotUpdatePanel使用了下面的ProgressBar1

生成代码之后提示找不到FUI_HotUpdatePanel

![QQ截图20230507120406](https://user-images.githubusercontent.com/111265430/236657149-abd0d351-8279-4f36-9fd1-b3597a045559.png)

![QQ截图20230507120418](https://user-images.githubusercontent.com/111265430/236657152-6fbc3d43-1343-42f4-b6c0-16c742bcd27e.png)

也就是代码自动生成了FUI_ProgressBar1。
如果将FairyGUI工程中的ProgressBar1设置为不导出，则FUIAutoGen下面不会生成HotUpdate文件夹。

我该怎么让他生成FUI_HotUpdatePanel而不是FUI_ProgressBar1？？？

**Comment by TapsJoy** [comment]
ProgressBar1删掉也还是不行，真神奇。

**Comment by TapsJoy** [comment]
懵了，新建面板也不能正确生成代码。好像有点问题。

**Comment by IcePower** [comment]
这里的确需要修改一下。
目前 FUI_HotUpdatePanel 没有生成，是因为 HotUpdatePanel 里都是默认的变量名，所以没有导出。你把HotUpdatePanel 里的progressbar 改个名字再试试吧。

**Comment by TapsJoy** [comment]
基本可以了。不过自定义的FUI不会在PanelId中自动创建，需要手动添加一下。
![QQ截图20230508211346](https://user-images.githubusercontent.com/111265430/236835067-2e868784-07af-48e2-bbfe-e727853d8968.png)

**Comment by IcePower** [comment]
应该不会啊，更新到最新后需要手动设置为主界面

**Comment by TapsJoy** [comment]
> 应该不会啊，更新到最新后需要手动设置为主界面

大佬牛逼，可以了，这下完美了。大佬辛苦了。
