### ISSUE TITLE
安卓打包成功后，什么都不显示

### ISSUE THREAD

**Issue by duckTyping** [IcePower/X-ET7#28]
<img width="957" alt="image" src="https://github.com/IcePower/X-ET7/assets/77422596/2e589955-60ec-40b9-a1cc-5f6a3c8c1812">
<img width="624" alt="image" src="https://github.com/IcePower/X-ET7/assets/77422596/12dd73b9-77e0-4e30-b544-038d0128b21c">
几乎算是空场景，我不知道打包过程中改了什么，我后来用ET7.2的库打包出来是正常的

**Comment by IcePower** [comment]
是不是 YooAsset 没有设置好？

**Comment by duckTyping** [comment]
> 

不清楚啥情况，重新拉了项目，重新导入需要的插件，居然好了。
