### ISSUE TITLE
官方示例导入报错

### ISSUE THREAD

**Issue by maxzxq** [IcePower/X-ET7#8]
using ;

namespace ET.Client
{
	[ComponentOf(typeof(FUIEntity))]
	public class BasicsPanel: Entity, IAwake
	{
		private FUI_BasicsPanel _fuiBasicsPanel;

		public FUI_BasicsPanel FUIBasicsPanel
		{
			get => _fuiBasicsPanel ??= (FUI_BasicsPanel)this.GetParent<FUIEntity>().GComponent;
		}
	}
}

fairygui官方示例，有很多按钮那个页面导入报错，上面是BasicsPanel.cs内容，using后面缺失；同时没有FUI_BasicsPanel 这个文件；

**Comment by maxzxq** [comment]
是不是只能生成简单的页面？

**Comment by yonly1314** [comment]
任意新增一个页面都会报错

**Comment by yonly1314** [comment]
页面必须包含自定义组件名称，不然会被忽略，无法生成对应的FUI_*Panel

**Comment by maxzxq** [comment]
谢谢
